version: '3'

tasks:
  default:
    cmds:
      - task --list
  run:
    desc: Run the app in development mode
    cmds:
      - yarn
      - yarn dev
  run-test-app:
    desc: Run the TestApp (used in component tests)
    cmds:
      - yarn
      - VITE_USE_TEST_APP=true yarn dev
  update-screenshots:
    aliases:
      - us
    desc: Update screenshots by running the Playwright component tests (in Docker)
    vars:
      PLAYWRIGHT_VERSION:
        sh: jq -r '.devDependencies."@playwright/experimental-ct-react" | sub("^\\^"; "")' package.json
    cmds:
      - >-
        docker run -it --rm 
        -p 9323:9323 
        -v $(pwd):$(pwd) 
        mcr.microsoft.com/playwright:v{{.PLAYWRIGHT_VERSION}}-jammy 
        sh -c "cd $(pwd) && yarn && yarn test-ct --update-snapshots"
  check-all:
    aliases:
      - ca
    desc: Run CI checks locally
    cmds:
      - yarn
      - yarn lint
      - yarn tsc
      - yarn test --run
      - yarn playwright install
      - yarn test-ct
  run-component-tests:
    aliases:
      - ct
    desc: Run component tests (with UI)
    cmds:
      - yarn
      - yarn test-ct --ui
  update-yarn:
    desc: Update yarn to the latest version
    cmds:
      - yarn set version latest
  prettier:
    desc: Run prettier on all applicable files
    cmds:
      - yarn prettier . --write
  prettier-check:
    desc: Check files conform to Prettier formatting
    cmds:
      - yarn prettier . --check
