version: '3'

tasks:
  default: task --list
  run:
    desc: Run the app in development mode
    cmds:
      - yarn
      - yarn dev
  run-test-app:
    desc: Run the TestApp (used in component tests)
    cmds:
      - yarn
      - VITE_USE_TEST_APP=true yarn dev
  update-screenshots:
    aliases:
      - us
    desc: Update screenshots by running the Playwright component tests (in Docker)
    vars:
      PLAYWRIGHT_VERSION:
        sh: jq -r '.devDependencies."@playwright/experimental-ct-react" | sub("^\\^"; "")' package.json
    cmds:
      - >-
        docker run -it --rm 
        -p 9323:9323 
        -v $(pwd):$(pwd) 
        mcr.microsoft.com/playwright:v{{.PLAYWRIGHT_VERSION}}-jammy 
        sh -c "cd $(pwd) && yarn && NODE_OPTIONS=--max_old_space_size=8192 yarn test-ct --update-snapshots"
  check-all:
    aliases:
      - ca
    desc: Run CI checks locally
    cmds:
      - yarn
      - yarn tsc
      - yarn lint
      - task: prettier-check
      - yarn test --run
      - yarn playwright install
      - yarn test-ct
  run-component-tests:
    aliases:
      - ct
    desc: Run component tests (with UI)
    cmds:
      - yarn
      - yarn playwright install
      - yarn test-ct --ui
  update-yarn:
    desc: Update yarn to the latest version
    cmds:
      - yarn set version latest
  prettier-fix:
    desc: Run prettier on all applicable files
    cmds:
      - yarn prettier . --write
  prettier-check:
    desc: Check files conform to Prettier formatting
    cmds:
      - yarn prettier . --check
  coverage:
    desc: Generate test coverage report
    dir: .
    cmds:
      - yarn
      - yarn coverage
      - open coverage/index.html
  coverage-ct:
    desc: Run component tests and generate coverage report
    cmds:
      - yarn
      - yarn playwright install
      - yarn test-ct
      - open report/coverage/index.html
  bump-asdf-versions:
    desc: Update asdf plugins
    dir: .
    cmds:
      - asdf plugin update --all
      - scripts/bump-asdf-versions.sh
      - asdf install
  lint:
    desc: Run ESLint
    cmds:
      - yarn
      - yarn lint
  tsc:
    desc: Check TypeScript types
    cmds:
      - yarn
      - yarn tsc
  bundle-visualizer:
    desc: Visualise bundle size
    cmds:
      - npx --yes vite-bundle-visualizer
