version: '3'

tasks:
  default:
    cmds:
      - task --list
  update-screenshots:
    aliases:
      - us
    desc: Update screenshots using Docker
    cmds:
      - docker run -it --rm -p 9323:9323 -v $(pwd):$(pwd) mcr.microsoft.com/playwright:v1.41.1-jammy sh -c "cd $(pwd) && yarn && yarn test-ct --update-snapshots"
  check-all:
    aliases:
      - ca
    desc: Run CI checks locally
    cmds:
      - yarn && yarn lint && yarn tsc && yarn test --run && yarn test-ct
  run-component-tests:
    aliases:
      - ct
    desc: Run component tests (with UI)
    cmds:
      - yarn && yarn test-ct --ui
