name: CI

permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Install asdf tools 📦
        uses: asdf-vm/actions/install@v4

      - name: Install dependencies 📦
        run: yarn install

      - name: Lint 🧹
        run: yarn lint

      - name: Check TypeScript types 📏
        run: yarn tsc

      - name: Check Prettier formatting 🧹
        run: task prettier-check

      - name: Run tests 🧪
        run: yarn test

      - name: Install Playwright Browsers 🌐
        run: yarn playwright install chromium firefox

      - name: Run component tests 🎭
        run: yarn test-ct

      - name: Upload test results if component tests fail 😭
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: playwright-report

      - name: Build 🏗️
        run: yarn build

      - name: Build Storybook 📚
        run: yarn build-storybook

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

  dependabot:
    name: Enable auto-merge for Dependabot PRs 🤖
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
